env:
  browser: false
  es6: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-multi-spaces: 0,
  no-console: 0,
  key-spacing: 0,
  comma-dangle: ["error", "never"],
  no-return-await: 0
}
